// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd-LjajYjHnOGUU6Mzz7btUglfOVy1AG4',
    appId: '1:773183307287:web:b051a0bf15c39164332652',
    messagingSenderId: '773183307287',
    projectId: 'z-flix-e6ae1',
    authDomain: 'z-flix-e6ae1.firebaseapp.com',
    storageBucket: 'z-flix-e6ae1.firebasestorage.app',
    measurementId: 'G-0W5ESBHXPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7lp-8LxhLIT0RdZoP7Gnll5DZnV4SPSc',
    appId: '1:773183307287:android:b35b8b3a18c71863332652',
    messagingSenderId: '773183307287',
    projectId: 'z-flix-e6ae1',
    storageBucket: 'z-flix-e6ae1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9igOBZqnneBYX___YZgqQpDGuEJuV-TQ',
    appId: '1:773183307287:ios:6c8eb2b1152f4518332652',
    messagingSenderId: '773183307287',
    projectId: 'z-flix-e6ae1',
    storageBucket: 'z-flix-e6ae1.firebasestorage.app',
    iosBundleId: 'com.example.zFlix',
  );
}
